[package]
name = "star"
description = "star enters a sandbox and extracts a tar from stdin into OUTPUT-DIR"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0.33"
libc = "0.2.158"
tar = "0.4.41"
